### ISSUE TITLE
[BUG] raise ValueError("Given winepath doesn't seem a valid Wine path.")

### ISSUE THREAD

**Issue by qasem-talaee** [bottlesdevs/libwine#4]
Hello.I want to use your package.I get the following error when creating the object.
`my_wine = Wine(winepath="/usr/bin/wine", wineprefix="/home/user/my-wine", verbose=3)`
I found the wine route by order `whereis`.
thanks.

**Comment by mirkobrombin** [comment]
libwine only supports stand-alone wine builds (not coming from the package manager). E.g. download Caffe from our wine repository and then point the winepath to its root

**Comment by qasem-talaee** [comment]
Ok.thank you.Finally i develop my wine class.Good luck

**Comment by mirkobrombin** [comment]
Nice!
